# -*- coding: utf-8 -*-
"""finale_visualisatie_heatmap/scatterplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UwWr0SBewUIVFOUz_wcElD7MH3fvSxd
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd "/content/drive/My Drive/Colab Notebooks/Python_Project/Python_Data"

import pandas as pd
import matplotlib.pyplot as plt


df_happy = pd.read_csv('Zufriedenheit_Index.csv', delimiter=';')
print(df_happy.head())

df_happy.info()

df_happy_clean = df_happy.copy()

variables_set = ['happy', 'debt', 'age', 'education', 'poverty', 'growth', 'labour_hour']

df_happy_clean = df_happy_clean[df_happy_clean.columns.tolist()]

df_happy_clean[variables_set] = df_happy_clean[variables_set].replace(",", ".", regex=True).astype("float")

print(df_happy_clean)

import matplotlib.pyplot as plt

for variables_set in ('happy', 'debt', 'age', 'education', 'poverty', 'growth', 'labour_hour'):
    # Sortieren der Daten
    df_happy_clean.sort_values(variables_set, inplace=True)

    # Erstellen des Scatterplots
    plt.figure(figsize=(12, 8))
    for i in range(len(df_happy_clean)):
        plt.scatter(df_happy_clean['Country'][i], df_happy_clean[variables_set][i], s=df_happy_clean[variables_set][i]*15, c='r', alpha=0.5, edgecolors='black')
        plt.annotate(df_happy_clean['Country'][i], (df_happy_clean['Country'][i], df_happy_clean[variables_set][i]))
    plt.xticks([])
    plt.ylabel(variables_set)
    plt.show()



print(df_happy_clean[['happy', 'debt', 'age', 'education', 'poverty', 'growth','labour_hour']].corr())

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate correlation matrix (assuming numeric columns)
corr_matrix = df_happy_clean[['happy', 'debt', 'age', 'education', 'poverty', 'growth','labour_hour']].corr()

# Create a heatmap using Seaborn
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.show()